
post http://localhost:5000/users
Content-Type: application/json

{
    "fullname": "Thando",
    "email": "thando@gmail.com",
    "password": "Thando",
    "phone_number": "0786696767"
}
###
post http://localhost:5000/users
Content-Type: application/json

{
    "fullname": "Hannah222",
    "email": "HannahDalwai222@gmail.com",
    "password": "HannahDalwai1234558",
    "phone_number": "074123456722"
}
###

post http://localhost:5000/users
Content-Type: application/json

{
    "fullname": "user",
    "email": "user1@gmail.com",
    "password": "User1234",
    "phone_number": "074123456722"
}


###
post http://localhost:5000/posts
Content-Type: application/json

{
    "title": "How to feel your feelings",
    "description": "what therapasts actually mean.",
    "category": "mental health",
    "img": "https://picsum.photos/1920",
    "date": 20,
    "author": "Hannah Dalwai"
}

###
post http://localhost:5000/posts
Content-Type: application/json

{
    "title": "2022 journal prompts",
    "description": "lorem",
    "category": "movement",
    "img": "https://i.postimg.cc/6QPCwKY2/bookicon.png",
    "date": 51,
    "author": "Hannah Dalwai"
}

###
GET http://localhost:5000/users
###
GET  http://localhost:5000/posts
###
DELETE http://localhost:8003/users/621e0a541e7934b55bbb1fcd
###
PATCH http://localhost:5000/
Content-Type: application/json

{
    "email": "email@gmail.com",
    "password": "email@gmail.com"
}
###
PATCH https://localhost:5000/users
Content-Type: application/json

{
   "email": "HannahDalwai222@gmail.com",
    "password": "HannahDalwai1234558"
}